-- +goose Up
CREATE TABLE feed_follows(
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  feed_id INTEGER REFERENCES feeds(id) ON DELETE CASCADE NOT NULL,
  UNIQUE(user_id, feed_id)
);

-- +goose Down
DROP TABLE feed_follows;